'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated. 
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On


Partial Public Class Delete

    '''<summary>
    '''ActivityLabel control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ActivityLabel As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''ActivityTextBox control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ActivityTextBox As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''TaskSubmitButton control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents TaskSubmitButton As Global.System.Web.UI.WebControls.Button

    '''<summary>
    '''FeedbackLabel control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents FeedbackLabel As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''PreviousPageButton control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents PreviousPageButton As Global.System.Web.UI.WebControls.Button

    '''<summary>
    '''NextPageButton control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents NextPageButton As Global.System.Web.UI.WebControls.Button

    '''<summary>
    '''AnswerHF control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents AnswerHF As Global.System.Web.UI.WebControls.HiddenField

    '''<summary>
    '''ExecuteHF control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ExecuteHF As Global.System.Web.UI.WebControls.HiddenField

    '''<summary>
    '''GridViewPanel control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents GridViewPanel As Global.System.Web.UI.WebControls.Panel

    '''<summary>
    '''SQLResultsGrid control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents SQLResultsGrid As Global.System.Web.UI.WebControls.GridView

    '''<summary>
    '''CustomerGrid control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents CustomerGrid As Global.System.Web.UI.WebControls.AccessDataSource
End Class
